name: A workflow for Bigeye Deltas
on:
  pull_request:
    branches:
      - 'deltas-testing'
env:
  DEV_DIR: python-scripts

jobs:
  run-bigeye-deltas:
    name: run-bigeye-deltas
    runs-on: ubuntu-latest
    steps:
      - name: Print inverted pyramid
        run: python ${{ env.DEV_DIR }}/deltas_run.py
        shell: sh
