name: A workflow for Bigeye Deltas
on:
  pull_request:
    branches:
      - 'deltas-testing'
env:
  DEV_DIR: python-scripts

jobs:
  run-bigeye-deltas:
    name: run-bigeye-deltas
    runs-on: ubuntu-latest
    steps:
      - name: Check-out current repository
        uses: actions/checkout@v2
        with:
          repository: WhiskersReneeWe/hello-github-actions

      - name: Print inverted pyramid
        run: python ${{ env.DEV_DIR }}/deltas_run.py
        shell: sh
